#!/usr/bin/env python3
import sys
import math
from math import *

#gestion d'error
if sys.argv[1] == '-h':
        print("USAGE\n    ./101pong x0 y0 z0 x1 y1 z1 n\n\nDESCRIPTION\n    x0 ball abscissa at time t - 1\n    y0 ball ordinate at time t - 1\n    z0 ball altitude at time t - 1\n    x1 ball abscissa at time t\n    y1 ball ordinate at time t\n    z1 ball altitude at time t\n    n time shift (greater than or equal to zero, integer)")
        sys.exit()
else:
    if len(sys.argv) != 8:
        print("error syntax")
        sys.exit(84)

#vecteur A
x0, y0 ,z0= float(sys.argv[1]), float(sys.argv[2]), float(sys.argv[3])

#vecteur A - 1
x1, y1, z1 = float(sys.argv[4]), float(sys.argv[5]), float(sys.argv[6])

#temps
t = int(sys.argv[7])

#calcul de velocite
vx = x1 - x0
vy = y1 - y0
vz = z1 - z0

#bien mettre les decimals
f1x ="{:.2f}".format(vx)
f1y ="{:.2f}".format(vy)
f1z ="{:.2f}".format(vz)

#affichage velocite
print("The velocity vector of the ball is:\n(" + f1x + ",", f1y + ",", f1z + ")")

#coordinate at time + t
cx = x1 + (t * vx)
cy = y1 + (t * vy)
cz = z1 + (t * vz)

#bien mettre les decimals
f2x ="{:.2f}".format(cx)
f2y ="{:.2f}".format(cy)
f2z ="{:.2f}".format(cz)

#affichage coordonnee + affichage cas d'erreur angle incident
rest = "{:.0f}".format(t)
print("At time t +", rest + ",ball coordinates will be:\n(" + f2x + ",", f2y + ",", f2z + ")")

#calcul incidence angle
a = 90 - (acos(abs(z1 - z0) / sqrt(pow(x1 - x0, 2) + pow(y1 - y0, 2) + pow(z1 - z0, 2))))*180/pi

#bien mettre les decimals
res ="{:.2f}".format(a)

#affichage incidence angle
if a == 0 or (-z1 / (z1 - z0)) < 0:
    print("The ball won't reach the paddle.")
else:
    print("The incidence angle is:\n" + res, "degrees")